//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsonsAddins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class MySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MySettings defaultInstance = ((MySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings())));
        
        public static MySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PEP_Preferences {
            get {
                return ((string)(this["PEP_Preferences"]));
            }
            set {
                this["PEP_Preferences"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""PipeEndPrepBCWindow"":true,""PipeEndPrepWindow"":false,""DebugSettingsCommand"":false,""DimensionTextWindow"":true,""DimensionPipeLineCommand"":true,""SelectPipeLineCommand"":true,""DebugGeometryCommand"":false,""FilterPipingElementsCommand"":true,""GetTotalPipeLengthCommand"":true,""ParameterManagerDockablePane"":true,""SelectAllElementsOfSystemCommand"":true,""SmartFlipCommand"":true}")]
        public string ComponentState_Preferences {
            get {
                return ((string)(this["ComponentState_Preferences"]));
            }
            set {
                this["ComponentState_Preferences"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"primaryDimensionTypeName\":\"C & B\",\"secondaryPipeDimensionTypeName\":\"C & B PIPE " +
            "w/dot\",\"secondaryAccessoryDimensionTypeName\":\"C & B FITTING w/dot\",\"secondaryFit" +
            "tingDimensionTypeName\":\"C & B FITTING w/dot\",\"secondaryOtherDimensionTypeName\":\"" +
            "C & B FITTING w/dot\",\"graphicsStyleNames\":[\"<Centerline>\",\"Pipes\",\"Pipe Fittings" +
            "\",\"zLines\"],\"flangeModeItems\":[{\"elementId\":7465461,\"Name\":\"DI FLG DBL\",\"Mode\":2" +
            "},{\"elementId\":7151319,\"Name\":\"DI FCA\",\"Mode\":2},{\"elementId\":4634124,\"Name\":\"Co" +
            "upling - Generic\",\"Mode\":0},{\"elementId\":7047513,\"Name\":\"DI CMJ LONG SLEEVE C153" +
            "\",\"Mode\":4},{\"elementId\":7230174,\"Name\":\"CS WELD GAP MP\",\"Mode\":0},{\"elementId\":" +
            "7230980,\"Name\":\"CS WELD GAP\",\"Mode\":0},{\"elementId\":7316050,\"Name\":\"DI FLG DBL f" +
            "or fillers\",\"Mode\":2},{\"elementId\":7316874,\"Name\":\"DI FLG DBL MP\",\"Mode\":2},{\"el" +
            "ementId\":7317685,\"Name\":\"DI FLG DBL UN LINKED\",\"Mode\":2},{\"elementId\":7320961,\"N" +
            "ame\":\"DI FLG SINGLE MP\",\"Mode\":2},{\"elementId\":7322565,\"Name\":\"DI FLG SINGLE\",\"M" +
            "ode\":2},{\"elementId\":7303217,\"Name\":\"DI FLG GASKET DO NOT SCHEDULE\",\"Mode\":2},{\"" +
            "elementId\":7315853,\"Name\":\"DI FLG GASKET\",\"Mode\":2},{\"elementId\":7319339,\"Name\":" +
            "\"DI FLG DBL WITH STUDS\",\"Mode\":2},{\"elementId\":7237273,\"Name\":\"SS WELD GAP\",\"Mod" +
            "e\":0},{\"elementId\":7252261,\"Name\":\"SS WELD GAP MP\",\"Mode\":0},{\"elementId\":458413" +
            "5,\"Name\":\"Non-Connector\",\"Mode\":0},{\"elementId\":7030191,\"Name\":\"Victaulic-Groove" +
            "d Coupling OGS-AGS_Face\",\"Mode\":2},{\"elementId\":7036679,\"Name\":\"DI HP LOK FITTIN" +
            "G BELL\",\"Mode\":3},{\"elementId\":7039212,\"Name\":\"DI MJ BELL\",\"Mode\":4},{\"elementId" +
            "\":7040062,\"Name\":\"DI PO BELL\",\"Mode\":4},{\"elementId\":7062627,\"Name\":\"Victaulic-A" +
            "WWA-Grooved Coupling\",\"Mode\":2},{\"elementId\":7063762,\"Name\":\"DI MJ LONG SLEEVE C" +
            "110\",\"Mode\":4},{\"elementId\":7105299,\"Name\":\"DI TRFLEX SLEEVE DOMESTIC\",\"Mode\":3}" +
            ",{\"elementId\":7123588,\"Name\":\"DI TRFLEX SLEEVE IMPORT\",\"Mode\":3},{\"elementId\":72" +
            "56569,\"Name\":\"DI TR FLEX FITTING BELL MP\",\"Mode\":3},{\"elementId\":7273137,\"Name\":" +
            "\"DI HP LOK FITTING BELL MP\",\"Mode\":3},{\"elementId\":7275670,\"Name\":\"DI MJ BELL MP" +
            "\",\"Mode\":4},{\"elementId\":7276520,\"Name\":\"DI PO BELL MP WITH FIELD LOK GASKET\",\"M" +
            "ode\":2},{\"elementId\":7279034,\"Name\":\"DI PO BELL MP\",\"Mode\":4},{\"elementId\":72844" +
            "98,\"Name\":\"Victaulic-AWWA-Coupling Style 31_MP\",\"Mode\":2},{\"elementId\":7286104,\"" +
            "Name\":\"DI VIC STYLE 31 CPLG_MP\",\"Mode\":2},{\"elementId\":7289129,\"Name\":\"DI VIC ST" +
            "YLE 31 CPLG\",\"Mode\":2},{\"elementId\":7292332,\"Name\":\"DI FLG GASKET w- STUDS\",\"Mod" +
            "e\":2},{\"elementId\":7306393,\"Name\":\"FLG PACK w TWO GASKETS & EX LONG STUDS w DBL " +
            "NUTS EA\",\"Mode\":2},{\"elementId\":7309215,\"Name\":\"DI HDSS BELL\",\"Mode\":3},{\"elemen" +
            "tId\":7311748,\"Name\":\"DI HDSS BELL MP\",\"Mode\":3},{\"elementId\":7314281,\"Name\":\"DI " +
            "FLG x VIC FLG STYLE 341\",\"Mode\":2},{\"elementId\":7321771,\"Name\":\"DI FLG SINGLE wo" +
            " GASKET\",\"Mode\":2},{\"elementId\":7466331,\"Name\":\"DI TR FLEX FITTING BELL\",\"Mode\":" +
            "3}]}")]
        public string DimensionStyles_Preferences {
            get {
                return ((string)(this["DimensionStyles_Preferences"]));
            }
            set {
                this["DimensionStyles_Preferences"] = value;
            }
        }
    }
}
